[package]
name = "uwmips"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
name = "uwmips"

[[bin]]
name = "uwmips"

[dependencies]
wasm-bindgen = "0.2.45"

[dev-dependencies]
wasm-bindgen-test = "0.2"